CXX=clang++
CXXFLAGS=-Wall -Wextra -pedantic -std=c++20

all: 6-0 6-1 6-2 6-3 6-4 6-5 6-6-7 

6-0: 6-0.cpp
	$(CXX) $(CXXFLAGS) 6-0.cpp -o 6-0
	./6-0

6-1: 6-1.cpp
	$(CXX) $(CXXFLAGS) 6-1.cpp -o 6-1
	./6-1
6-2: 6-2.cpp
	$(CXX) $(CXXFLAGS) 6-2.cpp -o 6-2
	./6-2
6-3: 6-3.cpp
	$(CXX) $(CXXFLAGS) 6-3.cpp -o 6-3
	./6-3
6-4: 6-4.cpp
	$(CXX) $(CXXFLAGS) 6-4.cpp -o 6-4
	./6-4

6-5: 6-5.cpp
	$(CXX) $(CXXFLAGS) 6-5.cpp -o 6-5
	./6-5

6-6-7: 6-6-7.cpp
	$(CXX) $(CXXFLAGS) 6-6-7.cpp -o 6-6-7
	./6-6-7

.PHONY: clean 6-0 6-1 6-2 6-3 6-4 6-5 6-6-7
clean:
	rm -f 6-0 6-1 6-2 6-3 6-4 6-5 6-6-7